### ISSUE TITLE
Commit and push local changes back to GitHub

### ISSUE THREAD

**Issue by dtinth** [dtinth/github-actions-snippets#1]
GitHub Actions can push commits back into the respository. Use cases include:

- [Automatically generating README file from GitHub Issues](https://github.com/dtinth/github-actions-snippets)
- [Creating a self-updating repository](https://github.com/dtinth/fresh-react-app)
- [Keeping app screenshots up-to-date](https://github.com/dtinth/timelapse)

```yaml
      - name: Push changes back to GitHub
        env:
          GIT_COMMITTER_NAME: Janitor
          GIT_AUTHOR_NAME: Janitor
          EMAIL: repository-janitor[bot]@users.noreply.github.com
        run: |
          git add --all \
            && git commit -m "Update $(node -p 'new Date().toJSON()')" \
            || echo "Nothing to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" "$GITHUB_REF"
```
