### ISSUE TITLE
Run a job only when commit message matches a certain keyword

### ISSUE THREAD

**Issue by dtinth** [dtinth/github-actions-snippets#5]
Useful when you want to save costs… especially macOS builds, which can be expensive. Sometimes building on every single commit may not be the best idea…

```yaml
jobs:
  build:
    if: "contains(github.event.head_commit.message, '[build]')"
```
